webroot/AutoSa/AutoSa/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from AutoSa import views
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'AutoSa.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    (r'^install/', views.install),
    (r'^$', views.index),
    (r'^login/$', views.login),
    (r'^logout/$', views.logout),
    (r'^showUser/$', views.showUser),
    (r'^addUser/$', views.addUser),
    (r'^chgUser/$', views.chgUser),
    (r'^showGroup/$', views.showGroup),
    (r'^addGroup/$', views.addGroup),
    (r'^chgGroup/$', views.chgGroup),
    (r'^showIDC/$', views.showIDC),
    (r'^addIDC/$', views.addIDC),
    (r'^addStatus/$', views.addStatus),
    (r'^addSort/$', views.addSort),
    (r'^chgIDC/$', views.chgIDC),
    (r'^showSudo/$', views.showSudo),
    (r'^chgSudo/$', views.chgSudo),
    (r'^showAssets/$', views.showAssets),
    (r'^addAssets/$', views.addAssets),
    (r'^showPerm/$', views.showPerm),
    (r'^addPerm/$', views.addPerm),
    (r'^downKey/$', views.downKey),
    (r'^chgPass/$', views.chgPass),
    (r'^chgKey/$', views.chgKey),
    (r'^upFile/$', views.upFile),
    (r'^downFile/$', views.downFile),
    (r'^logView/$', views.logView),
    (r'^logHistory/$', views.logHistory),
    (r'^killSession/$', views.killSession),
)

webroot/AutoSa/Assets/models.py
from django.db import models
from UserManage.models import User


class IDC(models.Model):
    name = models.CharField(max_length=20)

    def __unicode__(self):
        return self.name

class SERV_STATUS(models.Model):
    name = models.CharField(max_length=20)

    def __unicode__(self):
        return self.name

class SERV_SORT(models.Model):
    name = models.CharField(max_length=20)

    def __unicode__(self):
        return self.name


class Assets(models.Model):
    id = models.AutoField(primary_key=True)
    app = models.CharField(max_length=30)
    sort = models.ForeignKey(SERV_SORT)
    ip = models.CharField(max_length=20)
    memsize = models.IntegerField(max_length=4)
    disknum = models.IntegerField(max_length=4)
    port = models.IntegerField(max_length=5)
    idc = models.ForeignKey(IDC)
    status = models.ForeignKey(SERV_STATUS)
    type = models.CharField(max_length=20)
    instance = models.CharField(max_length=20)
    comment = models.CharField(max_length=100, blank=True, null=True)

    def __unicode__(self):
        return '%d %s ' % (self.id,self.ip)


class AssetsUser(models.Model):
    uid = models.ForeignKey(User)
    aid = models.ForeignKey(Assets)

webroot/AutoSa/UserManage/forms.py
# coding: utf-8

from django import forms
from UserManage.models import Group


class GroupAddForm(forms.Form):
    name = forms.CharField(max_length=30)


class UserAddForm(forms.Form):
    username = forms.CharField(max_length=30,
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control', 'placeholder': '用户名'}))
    password = forms.CharField(max_length=30,
                               widget=forms.PasswordInput(
                                   attrs={'class': 'form-control', 'placeholder': '密码'}))
    password_again = forms.CharField(max_length=30,
                                     widget=forms.PasswordInput(
                                         attrs={'class': 'form-control', 'placeholder': '确认密码'}))
    key_pass = forms.CharField(max_length=30, min_length=6,
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '密钥密码'}))
    key_pass_again = forms.CharField(max_length=30,
                                     widget=forms.PasswordInput(
                                         attrs={'class': 'form-control', 'placeholder': '确认密码'}))
    name = forms.CharField(max_length=30,
                           widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '姓名'}))
    group = forms.ModelMultipleChoiceField(queryset=Group.objects.all(),
                                           widget=forms.SelectMultiple(attrs={'class': 'form-control'}))
    is_admin = forms.BooleanField(required=False)
    is_superuser = forms.BooleanField(required=False)

    def clean_password_again(self):
        password = self.cleaned_data['password']
        password_again = self.cleaned_data['password_again']

        if password != password_again:
            raise forms.ValidationError(u'密码二次输入不一致. ')
        return password_again

    def clean_key_pass_again(self):
        key_pass = self.data['key_pass']
        key_pass_again = self.data['key_pass_again']
        if key_pass != key_pass_again:
            raise forms.ValidationError(u'密码二次输入不一致. ')
        if len(key_pass) < 6:
            raise forms.ValidationError(u'密码二次输入不一致. ')
        return key_pass_again

webroot/AutoSa/templates/addGroup.html
{% extends 'base.html' %}
{% block content %}
    <form class="form-horizontal" role="form" method="post" action="" >
        <fieldset >
            <legend>添加属组</legend>
            {% if error %}
                <div class="alert alert-danger">
                    {{ error }}
                </div>
            {% endif %}
            {% if msg %}
                <div class="alert alert-success">
                    {{ msg }}
                </div>
            {% endif %}
            <div class="form-group">
                <label for="name" class="col-sm-2 control-label">属组<span style="color: red"> *</span></label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" id="name" name="name" placeholder="属组">
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-4">
                    <button class="btn btn-primary">添加</button>
                </div>
            </div>
        </fieldset>
    </form>
{% endblock %}

webroot/AutoSa/templates/addIDC.html
{% extends 'base.html' %}
{% block content %}
    <form class="form-horizontal" role="form" method="post" action="" >
        <fieldset >
            <legend>添加机柜</legend>
            {% if error %}
                <div class="alert alert-danger">
                    {{ error }}
                </div>
            {% endif %}
            {% if msg %}
                <div class="alert alert-success">
                    {{ msg }}
                </div>
            {% endif %}
            <div class="form-group">
                <label for="name" class="col-sm-2 control-label">机柜编号<span style="color: red"> *</span></label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" id="name" name="name" placeholder="机柜编号">
                </div>

            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-4">
                    <button class="btn btn-primary">添加</button>
                </div>
            </div>
        </fieldset>
    </form>
{% endblock %}

webroot/AutoSa/templates/addPerm.html
{% extends 'base.html' %}
{% block content %}
    <form method="post" action="">
        {% if info %}
            <p class="alert alert-success">
                {{ info }}
            </p>
        {% endif %}
        <table class="table table-striped table-hover table-condensed">
        <thead>
            <tr>
                <th><input onclick="selectAll()" type="checkbox"  name="select_all" style="select_all" id="select_all"/></th>
                <th>ID</th>
                <th>用户</th>
                <th>服务器</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td style="width: 13px"><input type="checkbox" name="selected" value="{{ asset.id }}"></td>
                <td style="width: 5px">{{ user.id }}</td>
                <td style="width: 90px">{{ user.name }}</td>
                <td style="width: 90px"><a href="/addPerm/?username={{ user.username }}">添加权限</a></td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
        <button class="btn btn-success">删除</button></td>
    </form>

{% endblock %} %}

webroot/AutoSa/templates/addSort.html
{% extends 'base.html' %}
{% block content %}
    <form class="form-horizontal" role="form" method="post" action="" >
        <fieldset >
            <legend>添加应用分类</legend>
            {% if error %}
                <div class="alert alert-danger">
                    {{ error }}
                </div>
            {% endif %}
            {% if msg %}
                <div class="alert alert-success">
                    {{ msg }}
                </div>
            {% endif %}
            <div class="form-group">
                <label for="name" class="col-sm-2 control-label">应用分类<span style="color: red"> *</span></label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" id="name" name="name" placeholder="web/front/redis/rabbitmq..">
                </div>

            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-4">
                    <button class="btn btn-primary">添加</button>
                </div>
            </div>
        </fieldset>
    </form>
{% endblock %}

webroot/AutoSa/templates/addUser.html
{% extends 'base.html' %}
{% block content %}
    <form class="form-horizontal" role="form" method="post" action="" >
        <fieldset >
            <legend>添加用户</legend>
            {% if error %}
                <div class="alert alert-danger">
                    {{ error }}
                </div>
            {% endif %}

            {% if form.errors %}
                <div class="alert alert-danger">
                     Please correct the error{{ form.errors|pluralize }} below.
                </div>
            {% endif %}

            {% if msg %}
                <div class="alert alert-success">
                    {{ msg }}
                </div>
            {% endif %}
            <div class="form-group">
                {{ form.username.errors }}
                <label for="id_username" class="col-sm-2 control-label">用户名<span style="color: red"> *</span></label>
                <div class="col-sm-4">
                    {{ form.username }}
                </div>
            </div>
            <div class="form-group">
                {{ form.password.errors }}
                <label for="id_password" class="col-sm-2 control-label">密码<span style="color: red"> *</span></label>
                <div class="col-sm-4">
                    {{ form.password }}
                </div>
            </div>
            <div class="form-group">
                {{ form.password_again.errors }}
                <label for="id_password_again" class="col-sm-2 control-label">确认密码<span style="color: red"> *</span></label>
                <div class="col-sm-4">
                    {{ form.password_again }}
                </div>
            </div>
            <div class="form-group">
                {{ form.key_pass.errors }}
                <label for="id_keypass" class="col-sm-2 control-label">密钥密码<span style="color: red"> *</span></label>
                <div class="col-sm-4">
                    {{ form.key_pass }}
                </div>
            </div>
            <div class="form-group">
                {{ form.key_pass_again.errors }}
                <label for="id_keypass_again" class="col-sm-2 control-label">确认密码<span style="color: red"> *</span></label>
                <div class="col-sm-4">
                    {{ form.key_pass_again }}
                </div>
            </div>
            <div class="form-group">
                {{ form.name.errors }}
                <label for="id_name" class="col-sm-2 control-label">姓名<span style="color: red"> *</span></label>
                <div class="col-sm-4">
                    {{ form.name }}
                </div>
            </div>
            <div class="form-group">
                {{ form.group.errors }}
                <label for="id_group" class="col-sm-2 control-label">属组</label>
                <div class="col-sm-4">
                    {{ form.group }}
                </div>
                <div class="col-sm-4">
                    <a href="/addGroup/">添加属组</a>
                </div>
                <div class="col-sm-4">
                    <a href="/showGroup/">删除属组</a>
                </div>
            </div>
            <div class="form-group">
                {{ form.is_admin.errors }}
                <label for="id_is_admin" class="col-sm-2 control-label">组admin</label>
                <div class="col-sm-4">
                    {{ form.is_admin }}
                </div>
            </div>
            <div class="form-group">
                {{ form.is_superuser.errors }}
                <label for="id_is_superuser" class="col-sm-2 control-label">超级admin</label>
                <div class="col-sm-4">
                    {{ form.is_superuser }}
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-4">
                    <button class="btn btn-primary">添加</button>
                </div>
            </div>
        </fieldset>
    </form>
{% endblock %}

webroot/AutoSa/templates/addUserPerm.html
{% extends 'base.html' %}
{% block content %}
    <form method="post" class="form-horizontal" action="">
    <fieldset>
        <legend>{{ user.name }}</legend>
        {% if info %}
            <p class="alert alert-success">
                {{ info }}
            </p>
        {% endif %}
        <div class="form-group">
            <label for="username" class="col-sm-2 control-label">用户名</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="username" id="username" value="{{ user.username }}" disabled>
            </div>
            <input type="hidden" class="form-control" name="username" id="username" value="{{ user.username }}">
        </div>

        <div class="form-group">
            <label for="asset" class="col-sm-2 control-label">服务器</label>
            <div class="col-sm-10">
                <select multiple class="form-control add-perm" name="asset">
                {% for asset in assets %}
                    <option value="{{ asset.id }}">{{ asset.ip }}</option>
                {% endfor %}
                </select>
            </div>
         </div>

        <div class="from-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">添加</button>
            </div>
        </div>



    </fieldset>
    </form>
{% endblock %}

webroot/AutoSa/templates/chgSudo.html
{% extends 'base.html' %}
{% block content %}
        <fieldset >
            <legend>{{ username }}--修改sudo</legend>
            <form class="form-horizontal" role="form" method="post" action="/chgSudo/" >
               <div class="row">
                  <div class="col-lg-6">
                    <div class="input-group">
                      <input type="text" name="username" value="{{ username }}" hidden="hidden">
                      <input type="text" class="form-control" name="add_host" placeholder="主机IP,多个逗号分隔">
                      <span class="input-group-btn">
                        <button class="btn btn-success" type="submit">新增主机</button>
                      </span>
                    </div><!-- /input-group -->
                  </div><!-- /.col-lg-6 -->
                </div><!-- /.row -->
            </form>
            <br>

            <form class="form-horizontal" role="form" method="post" action="/chgSudo/" >
               <div class="row">
                  <div class="col-lg-6">
                    <div class="input-group">
                        <input type="text" name="username" value="{{ username }}" hidden="hidden">
                      <input type="text" class="form-control" name="del_host" placeholder="主机IP,多个逗号分隔">
                      <span class="input-group-btn">
                        <button class="btn btn-primary" type="submit">删除主机</button>
                      </span>
                    </div><!-- /input-group -->
                  </div><!-- /.col-lg-6 -->
                </div><!-- /.row -->
            </form>
            <br>

            <form class="form-horizontal" role="form" method="post" action="/chgSudo/" >
               <div class="row">
                  <div class="col-lg-6">
                    <div class="input-group">
                      <input type="text" name="username" value="{{ username }}" hidden="hidden">
                      <input type="text" class="form-control" name="add_cmd" placeholder="添加命令,多个逗号分隔">
                      <span class="input-group-btn">
                        <button class="btn btn-info" type="submit">添加命令</button>
                      </span>
                    </div><!-- /input-group -->
                  </div><!-- /.col-lg-6 -->
                </div><!-- /.row -->
            </form>
            <br>

            <form class="form-horizontal" role="form" method="post" action="/chgSudo/?delCMD=1" >
               <div class="row">
                  <div class="col-lg-6">
                    <div class="input-group">
                      <input type="text" name="username" value="{{ username }}" hidden="hidden">
                      <input type="text" class="form-control" name="del_cmd" placeholder="删除命令,多个逗号分隔">
                      <span class="input-group-btn">
                        <button class="btn btn-danger" type="submit">删除命令</button>
                      </span>
                    </div><!-- /input-group -->
                  </div><!-- /.col-lg-6 -->
                </div><!-- /.row -->
            </form>
        </fieldset>
{% endblock %}

webroot/AutoSa/templates/index.html
{% extends "base.html" %}
{% block content %}
{% if not admin %}
   <h1 style="color: green">说明：</h1>
   <p>1. 登陆密码：可以修改登陆本系统的密码</p>
   <p>2. 密钥密码：可以修改登陆服务器时密钥的密码</p>

   <p><b>我的密钥:</b> <a href="/downKey/">下载</a></p>
   <fieldset>
       <legend>我可登陆的服务器：</legend>
        <table class="table table-striped table-hover table-condensed">
        <thead>
            <tr>
                <th><input onclick="selectAll()" type="checkbox"   name="select_all" style="select_all" id="select_all"/></th>
                <th>ID</th>
                <th>IP</th>
                <th>Port</th>
                <th>机柜号</th>
                <th>备注</th>
            </tr>
        </thead>
        <tbody>
            {% for asset in assets %}
            <tr>
                <td style="width: 13px"><input type="checkbox" name="selected" value="{{ asset.id }}"></td>
                <td style="width: 5px">{{ asset.id }}</td>
                <td style="width: 90px">{{ asset.ip }}</td>
                <td style="width: 90px">{{ asset.port }}</td>
                <td style="width: 90px">{{ asset.idc }}</td>
                <td style="width: 90px">{{ asset.comment }}</td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
   </fieldset>
{% else %}
   <p>跳板机系统管理系统，负责添加用户，添加主机和用户权限，不要笑它简陋哦。</p>
   <p><a href="#" class="btn btn-primary btn-large">试试吧。 &raquo;</a></p>
{% endif %}
{% endblock %}

webroot/AutoSa/templates/logView.html
{% extends 'base.html' %}
{% load mytags %}

{% block content %}

    <form method="post" action="">
        <table class="table table-striped table-hover table-condensed">
        <thead>
            <tr>
                <th>id</th>
                <th>用户名</th>
                <th>主机</th>
                <th>监控</th>
                <th>命令统计</th>
                <th>阻断</th>
                <th>开始时间</th>
                <th>结束时间</th>
            </tr>
        </thead>
        <tbody>
            {% for log in logs.object_list %}
            <tr>
                <!--<td><input type="checkbox" name="selected" value="{{ log.id }}"></td>-->
                <td>{{ log.id }}</td>
                <td>{{ log.user }}</td>
                <td>{{ log.host }}</td>
                {% if log.finish %}
                <td>监控</td>
                <td><a href="/logHistory/?id={{ log.id }}" class="log_command">统计</a></td>
                <td>阻断</td>
                {% else %}
                <td><a class='monitor' filename="{{ log.logfile }}">监控</a></td>
                <td>命令统计</td>
                <td><a href="/killSession/?id={{ log.id }}">阻断</a> </td>
                {% endif %}
                <td>{{ log.start_time|stamp2str }}</td>
                <td>{{ log.end_time|stamp2str }}</td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
        <script src="http://{{ web_socket_host }}/socket.io/socket.io.js"></script>


        <script >
           $.fn.webSocket = function(opt){
            var st = {};
            st = $.extend(st,opt);
            var message = {};
            var $this = $(this);


            var genUid = function(){
                return new Date().getTime()+""+Math.floor(Math.random()*899+100);
            };

            var init = function(e){

                var socket = io.connect('ws://'+globalConfig.SOCKET_HOST);
                var node = $(e.target);
                message.id = genUid();
                message.filename = node.attr('filename');
                BootstrapDialog.show({message:function(){
                    var escapeString = function (html){
                        var elem = document.createElement('div')
                        var txt = document.createTextNode(html)
                        elem.appendChild(txt)
                        return elem.innerHTML;
                    }
                    var tag = $('<div id="log" style="height:300px;overflow: auto;"></div>');
                    //告诉服务器端有用户登录
                    socket.emit('login', {userid:message.id, filename:message.filename});
                    socket.on('message',function(obj){
                        //去除log中的颜色控制字符
                        var regx =  /\x1B\[([0-9]{1,3}((;[0-9]{1,3})*)?)?[m|K]/g;
                        tag.append('<p>'+escapeString(obj.content.replace(regx,''))+'</p>');
                        tag.animate({ scrollTop: tag[0].scrollHeight}, 1);
                    });
                    return tag[0];
                } ,
                    title:'实时监控:',
                    onhide:function(){
                        socket.emit('disconnect');
                }});
            }


            $this.on("click",function(e){
                init(e);
                return false;
            });

        }

           $('.log_command').on('click',function(){
               var url = $(this).attr('href');
                $.ajax({url:url,success:function(data){
                BootstrapDialog.show({title:'命令统计',message:data});
                }});
               return false;
            })
           globalConfig = {
                SOCKET_HOST: "{{ web_socket_host }}"
           }
           $(".monitor").webSocket()

        </script>
    <!--<button class="btn btn-primary">删除</button>-->
    </form>
        <nav>
          <ul class="pager">
            {% if logs.has_previous %}
            <li><a href="?page={{ logs.previous_page_number }}">上一页</a></li>
            {% endif %}

            <span class="current">
             Page {{ logs.number }} of {{ logs.paginator.num_pages }}.
            </span>

            {% if logs.has_next %}
            <li><a href="?page={{ logs.next_page_number }}">下一页</a></li>
            {% endif %}
          </ul>
        </nav>
{% endblock %}

webroot/AutoSa/templates/login.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>登录</title>
<link href="/static/css/bootstrap.css" rel="stylesheet">
<link href="/static/css/main.css" rel="stylesheet">
<meta name="viewport" content="width=device-wdith,initial-scale=1.0">
<link rel="shortcut icon" href="http://www.10086.cn/favicon.ico" type="images/x-icon" />
<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5js"></script>
<![endif]-->

<style>
<!--
body {
	padding-top: 200px;
	padding-bottom: 40px;
	background-color: #eee;
}
-->
</style>
</head>

<body>
<div class="container">

  <div class="row">
    <div class="col-md-4 col-md-offset-3">
    {% if error %}
      <div class="alert alert-danger">
        {{ error }}
      </div>
    {% else %}
       <p>&nbsp;</p>
    {% endif %}
    </div>
  </div>

  <form class="form-horizontal" role="form" action="" method="post">
    <div class="row">
      <div class="form-group">
        <label for="username" class="col-md-1 col-md-offset-3 control-label">用户名</label>
        <div class="col-md-3">
          <input  class="form-control" id="username" name="username" placeholder="用户名">
        </div>
      </div>
    </div>
    <div class="row">
      <div class="form-group">
        <label for="password" class="col-md-1 col-md-offset-3 control-label">密&nbsp&nbsp&nbsp&nbsp码</label>
        <div class="col-md-3">
          <input type="password" class="form-control" id="password" name="password" placeholder="密码">
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-3 col-md-offset-4">
        <button type="submit" class="btn btn-success btn-block">
            <span>登录</span>
        </button>
      </div>
    </div>
  </form>
</div>
<script src="/static/js/bootstrap.js"></script> 
<script src="/static/js/jquery-1.11.1.min.js"></script>
</body>
</html>

webroot/AutoSa/templates/showAssets.html
{% extends 'base.html' %}
{% block content %}
    <form method="post" action="">
        {% if info %}
            <p class="alert alert-success">
                {{ info }}
            </p>
        {% endif %}
        <table class="table table-striped table-hover table-condensed">
        <thead>
            <tr>
                <th><input onclick="selectAll()" type="checkbox"   name="select_all" style="select_all" id="select_all"/></th>
                <th>ID</th>
                <th>IP</th>
                <th>项目</th>
                <th>分类</th>
                <th>内存</th>
                <th>磁盘</th>
                <th>Port</th>
                <th>机柜</th>
                <th>状态</th>
                <th>类型</th>
                <th>实例名</th>
                <th>备注</th>

            </tr>
        </thead>
        <tbody>
            {% for asset in assets %}
            <tr>
                <td style="width: 13px"><input type="checkbox" name="selected" value="{{ asset.id }}"></td>
                <td style="width: 5px">{{ asset.id }}</td>
                <td style="width: 90px">{{ asset.ip }}</td>
                <td style="width: 90px">{{ asset.app }}</td>
                <td style="width: 90px">{{ asset.sort }}</td>
                <td style="width: 90px">{{ asset.memsize }}</td>
                <td style="width: 90px">{{ asset.disknum }}</td>
                <td style="width: 90px">{{ asset.port }}</td>
                <td style="width: 90px">{{ asset.idc }}</td>
                <td style="width: 90px">{{ asset.status }}</td>
                <td style="width: 90px">{{ asset.type }}</td>
                <td style="width: 90px">{{ asset.instance }}</td>
                <td style="width: 90px">{{ asset.comment }}</td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
        <button class="btn btn-primary">删除</button></td>
    </form>
       <nav>
          <ul class="pager">
            {% if assets.has_previous %}
            <li><a href="?page={{ assets.previous_page_number }}">上一页</a></li>
            {% endif %}

            <span class="current">
             Page {{ assets.number }} of {{ assets.paginator.num_pages }}.
            </span>

            {% if assets.has_next %}
            <li><a href="?page={{ assets.next_page_number }}">下一页</a></li>
            {% endif %}
          </ul>
        </nav>
{% endblock %}

webroot/AutoSa/templates/showIDC.html
{% extends 'base.html' %}
{% block content %}
    <form method="post" action="">
        {% if info %}
            <p class="alert alert-success">
                {{ info }}
            </p>
        {% endif %}
        <table class="table table-striped table-hover table-condensed">
        <thead>
            <tr>
                <th><input onclick="selectAll()" type="checkbox"  name="select_all" style="select_all" id="select_all"/></th>
                <th>ID</th>
                <th>机柜编号</th>
                <th>修改</th>
            </tr>
        </thead>
        <tbody>
            {% for idc in idcs %}
            <tr>
                <td><input type="checkbox" name="selected" value="{{ idc.id }}"></td>
                <td>{{ idc.id }}</td>
                <td>{{ idc.name }}</td>
                <td><a href="/chgIDC/?id={{ idc.id }}">修改</a></td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
    <button class="btn btn-primary">删除</button>
    </form>
{% endblock %}

webroot/AutoSa/templates/showPerm.html
{% extends 'base.html' %}
{% block content %}
    <form method="post" action="">
        {% if info %}
            <p class="alert alert-success">
                {{ info }}
            </p>
        {% endif %}
        <table class="table table-striped table-hover table-condensed">
        <thead>
            <tr>
                <th><input onclick="selectAll()" type="checkbox"  name="select_all" style="select_all" id="select_all"/></th>
                <th>ID</th>
                <th>用户</th>
                <th>服务器</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td style="width: 13px"><input type="checkbox" name="selected" value="{{ asset.id }}"></td>
                <td style="width: 5px">{{ user.id }}</td>
                <td style="width: 90px">{{ user.name }}</td>
                <td style="width: 90px"><a href="/showPerm/?username={{ user.username }}">查看列表</a></td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
        <button class="btn btn-primary">删除</button></td>
    </form>

{% endblock %}